name: Typecheck using Mypy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mypy:
    if: github.repository_owner == 'QCFD-Lab'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
          architecture: x64
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ${{ env.pythonLocation }}
          key: pip-typecheck-3.12.5-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-typecheck-3.12.5-
      - name: Install mypy
        run: |
          pip install --upgrade pip
          pip install -e .[cpu,dev]
      - name: Run mypy
        run: mypy qlbm test --config-file pyproject.toml
